# Lunar Horizon Optimizer - Advanced Powered Descent Mission Scenario
# This scenario demonstrates comprehensive lunar landing mission optimization 
# with powered descent cost modeling, multi-objective optimization, and economic analysis

description: "Lunar landing scenario with powered-descent optimization and economic analysis. This scenario models a Blue Origin lunar cargo mission with reusable lander technology, demonstrating comprehensive cost optimization including propellant consumption, hardware amortization, and learning curve effects in the commercial lunar economy."

# Mission configuration - orbital mechanics and trajectory parameters  
mission:
  name: "Blue Origin Lunar Cargo Express"
  description: "Commercial lunar cargo delivery using Blue Moon heritage lander with reusability and cost optimization focus"
  departure_epoch: 10000.0               # days since J2000 epoch
  earth_parking_orbit_altitude: 350.0    # km - optimized for New Glenn
  moon_parking_orbit_altitude: 80.0      # km - low lunar orbit for efficiency  
  transfer_time: 4.8                     # days - optimized trajectory
  launch_date: "2027-09-20"
  mission_duration_days: 150
  payload_description: "Base construction equipment and life support supplies"
  mission_type: "cargo_delivery"

# Powered descent parameters - landing propulsion system
descent_parameters:
  thrust: 24000.0                        # N - BE-7 engine cluster
  isp: 345.0                            # s - vacuum specific impulse 
  burn_time: 420.0                      # s - 7 minute powered descent
  landing_site: "Mare Imbrium"
  engine_type: "BE-7"
  propellant_type: "methane_oxygen"
  guidance_mode: "precision_landing"
  landing_accuracy_target: 50.0         # meters - 3-sigma accuracy
  number_of_engines: 1
  throttle_capability:
    min: 0.2                            # 20% minimum throttle
    max: 1.0                            # 100% maximum throttle
  fuel_margin: 0.08                     # 8% propellant reserve

# Optimization configuration - multi-objective optimization settings
optimizer:
  algorithm: "NSGA-II"
  pop_size: 50                          # population size for optimization
  generations: 30                       # number of generations
  include_descent: true                 # enable powered descent optimization
  objectives:
    - "minimize_delta_v"
    - "minimize_time" 
    - "minimize_cost"
  seed: 54321
  constraints:
    max_g_load: 3.5                     # g - structural acceleration limit
    min_fuel_reserve: 0.05              # 5% minimum propellant reserve
    max_landing_velocity: 2.0           # m/s - touchdown velocity limit
    max_lateral_velocity: 1.0           # m/s - horizontal velocity limit

# Economic analysis parameters - financial modeling and cost factors
economics:
  discount_rate: 0.06                   # 6% annual discount rate
  propellant_unit_cost: 16.0           # $/kg - liquid methane/LOX blend
  lander_fixed_cost: 8500000.0         # $8.5M - reusable lander unit cost
  inflation_rate: 0.025                # 2.5% annual inflation
  tax_rate: 0.21                       # 21% corporate tax rate
  project_duration_years: 10           # years - project lifetime
  
  # Revenue model
  revenue:
    cargo_delivery_rate_per_kg: 2800.0  # $/kg delivered to surface
    annual_missions: 4                  # missions per year by year 5
    mission_success_rate: 0.97          # 97% success probability
    nasa_contract_value: 800000000.0    # $800M NASA contract
    esa_contract_value: 450000000.0     # $450M ESA contract
    commercial_contract_value: 650000000.0  # $650M commercial contracts
  
  # Cost reduction modeling
  learning_curve:
    learning_rate: 0.88                 # 12% cost reduction per doubling
    initial_mission_cost: 160000000.0   # $160M first mission cost
    cost_reduction_per_doubling: 0.12   # 12% reduction
    reusability_factor: 0.40            # 40% cost reduction from reuse
    
  # Market projections
  market_analysis:
    initial_market_size: 15.0           # metric tons/year to lunar surface
    annual_growth_rate: 0.18            # 18% market growth
    target_market_share: 0.35           # 35% market share goal
    competitive_pressure: 0.75          # competition intensity factor

# Spacecraft configuration - vehicle specifications
spacecraft:
  name: "Blue Moon Cargo Variant"
  dry_mass: 8200.0                      # kg - Blue Moon derivative design
  payload_mass: 3300.0                 # kg - enhanced cargo capacity
  max_propellant_mass: 6500.0          # kg - increased tank capacity
  specific_impulse: 335.0               # s - BE-7 engine performance
  propulsion_type: "liquid_methane_lox"
  manufacturer: "Blue Origin"
  heritage: "Blue Moon HLS"

# Cost model parameters - economic factors and pricing
costs:
  launch_cost_per_kg: 5500.0           # $/kg - New Glenn heavy lift
  operations_cost_per_day: 55000.0     # $/day - reduced through automation
  development_cost: 650000000.0        # $650M total program cost
  contingency_percentage: 22.0         # % - commercial risk profile
  learning_rate: 0.88                  # Wright's law for cost reduction
  carbon_price_per_ton_co2: 80.0       # $/tCO2 - carbon offset pricing
  co2_emissions_per_kg_payload: 1.2    # tCO2/kg - methane is cleaner
  discount_rate: 0.06                  # 6% annual discount rate
  
  # Additional cost factors
  insurance_rate: 0.08                 # 8% of mission value
  refurbishment_cost: 1200000.0        # $1.2M between flights
  ground_support_cost: 45000.0         # $/day ground operations

# Orbital parameters - target orbit specification
orbit:
  type: "NRHO"                          # Near Rectilinear Halo Orbit
  semi_major_axis: 7152.0               # km - NRHO semi-major axis
  eccentricity: 0.95                    # high eccentricity for NRHO
  inclination: 57.0                     # degrees - southern access
  raan: 0.0                            # degrees - right ascension
  argument_of_periapsis: 180.0          # degrees - argument of periapsis
  true_anomaly: 0.0                     # degrees - initial position

# Optimization bounds and constraints
optimization:
  population_size: 50                   # NSGA-II population size
  num_generations: 30                   # optimization generations
  seed: 54321                          # random seed for reproducibility
  min_earth_alt: 200.0                 # km - minimum Earth orbit altitude
  max_earth_alt: 600.0                 # km - maximum Earth orbit altitude
  min_moon_alt: 50.0                   # km - minimum lunar orbit altitude
  max_moon_alt: 200.0                  # km - maximum lunar orbit altitude
  min_transfer_time: 3.5               # days - minimum transfer time
  max_transfer_time: 7.0               # days - maximum transfer time

# Expected performance metrics and validation targets
expected_results:
  total_mission_cost_range: "$155M - $180M"
  descent_cost_fraction: "5% - 7%"
  optimal_delta_v: "3100 - 3350 m/s"
  optimal_transfer_time: "4.6 - 5.2 days"
  propellant_mass_descent: "165 - 195 kg"
  lander_hardware_cost: "$8.5M amortized"
  roi_range: "22% - 28%"
  payback_period: "5 - 7 years"
  mission_success_probability: "97%"
  landing_accuracy: "50m (3-sigma)"
  cost_per_kg_delivered: "$2600 - $2900"

# Risk assessment parameters
risk_analysis:
  technical_risks:
    engine_reliability: 0.98           # 98% engine success rate
    landing_system_reliability: 0.97   # 97% landing success
    guidance_accuracy: 0.95            # 95% within target accuracy
  schedule_risk: 0.12                  # 12% schedule slip probability
  cost_overrun_risk: 0.18             # 18% cost overrun probability
  market_demand_uncertainty: 0.25     # 25% demand variation
  competition_risk: 0.30              # 30% competitive pressure

# Performance targets and mission success criteria
performance_targets:
  payload_fraction: 0.28               # 28% payload to total mass
  specific_cost: 2700.0               # $/kg to lunar surface
  turnaround_time: 45                  # days between missions
  mission_success_rate: 0.97          # 97% overall success target
  cost_reduction_trajectory: 0.12     # 12% cost reduction per doubling
  reusability_cycles: 5               # 5 flights per lander minimum

# Scenario metadata for classification and management
scenario_metadata:
  complexity: "Advanced"
  runtime_estimate: "90-120 seconds"
  mission_type: "Commercial Cargo"
  modules_used:
    - "trajectory.lunar_transfer"
    - "optimization.global_optimizer"
    - "economics.financial_models" 
    - "optimization.cost_integration"
    - "economics.isru_benefits"
  created_date: "2025-07-14"
  version: "2.0"
  author: "Mission Planning Team"
  validation_status: "verified"